<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'About' => 'Про нас',
    'Add new task' => 'Додати нову задачу',
    'Are you sure you want to delete this item?' => 'Ви впевнені що хочете виалити?',
    'Avatar' => 'Аватар',
    'Back to List' => 'До списку',
    'Can\'t delete user.' => 'Не можу видалити користувача',
    'Close' => 'Закрити',
    'Create Desk' => 'Створити Дошку',
    'Create Task' => 'Створити Задачу',
    'Create User' => 'Створити користувача',
    'Created At' => 'Дата створення',
    'Customer' => 'Замовник',
    'Delete' => 'Видалити',
    'Deleted' => 'Видалено',
    'Deleted Task: {name}' => 'Видалtyj задачу: {name}',
    'Desk' => 'Дошка',
    'Desk preference' => 'Налаштування дошки',
    'Desks' => 'Дошки',
    'Developer' => 'Розробник',
    'E-Mail' => 'E-Mail',
    'Home' => 'Додому',
    'ID' => 'ID',
    'Incorrect username or password.' => 'Неправильне гасло, або ім\'я',
    'Login' => 'Логін',
    'Logout' => 'Вийти',
    'Manager' => 'Менеджер',
    'Name' => 'Iм\'я',
    'Note' => 'Опис',
    'Password' => 'Гасло',
    'Please select' => 'Будь ласка виберіть',
    'Reset' => 'Скинути',
    'Role' => 'Роль',
    'Save' => 'Зберегти',
    'Search' => 'Пошук',
    'Sort' => 'Сорт',
    'Tasks' => 'Задачі',
    'The requested page does not exist.' => 'Запрошена сторінка не існує',
    'Update' => 'Редагувати',
    'Update Desk: {name}' => 'Оновити дошку: {name}',
    'Update Task: {name}' => 'Оновити задачу: {name}',
    'Update User: {name}' => 'Оновити Користувача: {name}',
    'User' => 'Користувач',
    'User List' => 'Списк користувачів',
    'User created successfully.' => 'Користувача успішер додано.',
    'User deleted successfully.' => 'Користувача успішно видалено',
    'User model: Error list type.' => 'Модель користувача: помилка списку типів',
    'User updated successfully.' => 'Користувача оновлено успішно.',
    'Users' => 'Користувачі',
    'View' => 'Переглянути',
    'View Task' => 'Переглянути задачу',
    'Remeber me' => 'Запам\'ятати мене',
];
